version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../nginx:/workspace           # Updated nginx path
      - $HOME/.aws:/root/.aws





volumes:
  jenkins_home:

